apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
        - name: employee-service
          image: asia-south1-docker.pkg.dev/ers-omesh/ers-repo/employee-service:latest
          ports:
            - containerPort: 8093
          env:
            - name: EUREKA_URL
              value: "http://eureka-server:8761/eureka/"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.0
          args:
            - "--structured-logs"
            - "ers-omesh:asia-south1:ers-postgres"
          securityContext:
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee-service
  ports:
    - port: 8093
      targetPort: 8093
  type: ClusterIP